import { useMemo, useState } from "react";
import { api } from "./api";
import type { CatalogCache, DesiredModel, ModelSummary } from "./types";

type Sort = "popular" | "newest" | "input" | "output" | "context" | "az";
const PAGE_SIZE = 50;
const price = (model: ModelSummary, key: "prompt" | "completion") => {
  const raw = model.pricing && typeof model.pricing === "object" ? (model.pricing as Record<string, unknown>)[key] : null;
  const parsed = typeof raw === "string" ? Number(raw) : raw;
  return typeof parsed === "number" && Number.isFinite(parsed) ? parsed * 1_000_000 : null;
};
const money = (number: number | null) => number === null ? "—" : number === 0 ? "Free" : `$${number.toLocaleString(undefined, { maximumFractionDigits: 4 })} / M`;
const compact = (tokens: number | null) => !tokens ? "—" : tokens >= 1_000_000 ? `${(tokens / 1_000_000).toFixed(tokens % 1_000_000 ? 1 : 0)}M` : `${Math.round(tokens / 1_000)}K`;
function capabilities(model: ModelSummary): string[] {
  const fields = new Set((model.supportedParameters ?? []).map((item) => item.toLowerCase())); const badges: string[] = [];
  if (["tools", "tool_choice", "tool_calls"].some((item) => fields.has(item))) badges.push("Tools");
  if (["response_format", "structured_outputs", "json_schema"].some((item) => fields.has(item))) badges.push("Structured Output");
  if (["reasoning", "reasoning_effort"].some((item) => fields.has(item))) badges.push("Reasoning");
  if ((model.inputModalities ?? []).some((item) => ["image", "video"].includes(item.toLowerCase()))) badges.push("Vision");
  return badges;
}

export function AllModelsPage({ models, desired, cache, refreshModels, onOpen, onDesiredChange, setError }: { models: ModelSummary[]; desired: DesiredModel[]; cache: CatalogCache | null; refreshModels: () => Promise<void>; onOpen: (id: string) => void; onDesiredChange: () => void; setError: (value: string) => void }) {
  const [query, setQuery] = useState(""); const [creator, setCreator] = useState(""); const [modality, setModality] = useState(""); const [minimumContext, setMinimumContext] = useState(0); const [maxInput, setMaxInput] = useState(""); const [maxOutput, setMaxOutput] = useState(""); const [freeOnly, setFreeOnly] = useState(false); const [capability, setCapability] = useState(""); const [sort, setSort] = useState<Sort>("popular"); const [page, setPage] = useState(0);
  const desiredIds = useMemo(() => new Set(desired.map((item) => item.modelId)), [desired]);
  const creators = useMemo(() => [...new Set(models.map((model) => model.creator).filter((item): item is string => Boolean(item)))].sort(), [models]);
  const filtered = useMemo(() => models.filter((model) => {
    const text = `${model.id} ${model.name ?? ""} ${model.creator ?? ""} ${model.description ?? ""}`.toLowerCase(); const input = price(model, "prompt"); const output = price(model, "completion");
    return (!query || text.includes(query.toLowerCase())) && (!creator || model.creator === creator) && (!modality || (model.inputModalities ?? []).some((item) => item.toLowerCase() === modality)) && (!minimumContext || (model.contextLength ?? 0) >= minimumContext) && (!maxInput || (input !== null && input <= Number(maxInput))) && (!maxOutput || (output !== null && output <= Number(maxOutput))) && (!freeOnly || (input === 0 && output === 0)) && (!capability || capabilities(model).includes(capability));
  }).sort((a, b) => {
    const numeric = (left: number | null, right: number | null, desc = false) => ((left ?? (desc ? -Infinity : Infinity)) - (right ?? (desc ? -Infinity : Infinity))) * (desc ? -1 : 1);
    if (sort === "newest") return numeric(a.created ?? null, b.created ?? null, true) || a.id.localeCompare(b.id);
    if (sort === "input") return numeric(price(a, "prompt"), price(b, "prompt")) || a.id.localeCompare(b.id);
    if (sort === "output") return numeric(price(a, "completion"), price(b, "completion")) || a.id.localeCompare(b.id);
    if (sort === "context") return numeric(a.contextLength, b.contextLength, true) || a.id.localeCompare(b.id);
    return `${a.name ?? a.id}`.localeCompare(`${b.name ?? b.id}`);
  }), [models, query, creator, modality, minimumContext, maxInput, maxOutput, freeOnly, capability, sort]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const resetPage = (fn: () => void) => { fn(); setPage(0); };
  const toggle = async (id: string) => { try { if (desiredIds.has(id)) { if (!window.confirm("Remove this Desired Model? This immediately revokes it from Local Access Keys and removes its per-key provider overrides.")) return; await api.removeDesiredModel(id); } else await api.addDesiredModel(id); onDesiredChange(); } catch (error) { setError((error as Error).message); } };
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">Catalog</p><h1>All Models</h1><p>Browse the local OpenRouter model snapshot. Provider performance loads only after a model is opened.</p></div><button className="button secondary" onClick={() => void refreshModels()}>Refresh catalog</button></div>
    {cache?.stale && <div className="catalog-state" role="status">Showing a stale local snapshot from {cache.fetchedAt ? new Date(cache.fetchedAt).toLocaleString() : "an unknown time"}.</div>}
    <div className="catalog-controls"><input aria-label="Search models" value={query} onChange={(event) => resetPage(() => setQuery(event.target.value))} placeholder="Search ID, name, creator, or description" /><select aria-label="Creator" value={creator} onChange={(event) => resetPage(() => setCreator(event.target.value))}><option value="">All creators</option>{creators.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Modality" value={modality} onChange={(event) => resetPage(() => setModality(event.target.value))}><option value="">All modalities</option><option value="text">Text</option><option value="image">Image</option><option value="audio">Audio</option><option value="video">Video</option></select><select aria-label="Context length" value={minimumContext} onChange={(event) => resetPage(() => setMinimumContext(Number(event.target.value)))}><option value="0">Any context</option><option value="32000">≥ 32K</option><option value="64000">≥ 64K</option><option value="128000">≥ 128K</option><option value="256000">≥ 256K</option><option value="1000000">≥ 1M</option></select><input aria-label="Maximum input price per million" type="number" min="0" value={maxInput} onChange={(event) => resetPage(() => setMaxInput(event.target.value))} placeholder="Max input $/M" /><input aria-label="Maximum output price per million" type="number" min="0" value={maxOutput} onChange={(event) => resetPage(() => setMaxOutput(event.target.value))} placeholder="Max output $/M" /><select aria-label="Capability" value={capability} onChange={(event) => resetPage(() => setCapability(event.target.value))}><option value="">All capabilities</option><option>Tools</option><option>Structured Output</option><option>Reasoning</option><option>Vision</option></select><label className="catalog-checkbox"><input type="checkbox" checked={freeOnly} onChange={(event) => resetPage(() => setFreeOnly(event.target.checked))} />Free only</label><select aria-label="Sort models" value={sort} onChange={(event) => resetPage(() => setSort(event.target.value as Sort))}><option value="popular">Popular / default</option><option value="newest">Newest</option><option value="input">Lowest input price</option><option value="output">Lowest output price</option><option value="context">Largest context</option><option value="az">A–Z</option></select></div>
    {!cache?.available && models.length === 0 ? <div className="empty"><h2>No cached models yet</h2><p>Configure an OpenRouter key outside the UI, then refresh the catalog.</p></div> : <><p className="catalog-count">{filtered.length} of {models.length} models · page {Math.min(page + 1, pageCount)} of {pageCount}</p><div className="model-list catalog-list">{visible.length === 0 ? <div className="empty"><h2>No models match these filters</h2><p>Clear one or more filters to broaden the local catalog.</p></div> : visible.map((model) => <article className="model-row catalog-row" key={model.id}><button className="model-link" onClick={() => onOpen(model.id)}><strong>{model.name || model.id}</strong><small>{model.creator ?? "Unknown creator"} · {model.id}</small><span className="catalog-inline"><span>{compact(model.contextLength)} context</span><span>In {money(price(model, "prompt"))}</span><span>Out {money(price(model, "completion"))}</span></span><span className="catalog-badges">{(model.inputModalities ?? []).slice(0, 3).map((item) => <i key={item}>{item}</i>)}{capabilities(model).map((item) => <i key={item}>{item}</i>)}</span></button><span className="model-meta"><button className={desiredIds.has(model.id) ? "desired-button selected" : "desired-button"} onClick={() => void toggle(model.id)}>{desiredIds.has(model.id) ? "✓ Desired" : "Add to Desired"}</button></span></article>)}</div><div className="catalog-pagination"><button className="button secondary" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><button className="button secondary" disabled={page + 1 >= pageCount} onClick={() => setPage(page + 1)}>Next</button></div></>}
  </section>;
}
