import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import { Badge, Breadcrumbs } from "./components";
import type { DesiredModel, Endpoint, FilterOperator, FilterPreview, FilterPreviewEndpoint, FilterPreviewReason, ProviderFilterCondition, ProviderFilterConfig, ModelSummary } from "./types";

type Field = { id: string; label: string; type: "number" | "text" | "boolean"; unit?: string; operators: FilterOperator[] };
const baseFields: Field[] = ["p50", "p75", "p90", "p99"].flatMap((p) => [{ id: `performance.throughput.${p}`, label: `Throughput ${p.toUpperCase()}`, type: "number" as const, unit: "t/s", operators: ["gte", "lte"] as FilterOperator[] }, { id: `performance.latency.${p}`, label: `Latency ${p.toUpperCase()}`, type: "number" as const, unit: "s", operators: ["lte", "gte"] as FilterOperator[] }]).concat([
  ...["5m", "30m", "1d"].map((window) => ({ id: `uptime.${window}`, label: `Uptime ${window}`, type: "number" as const, unit: "%", operators: ["gte", "lte"] as FilterOperator[] })),
  { id: "quantization", label: "Quantization", type: "text", operators: ["eq", "in"] }, { id: "context.length", label: "Context Length", type: "number", unit: "tokens", operators: ["gte", "lte"] }, { id: "context.maxPrompt", label: "Max Prompt Tokens", type: "number", unit: "tokens", operators: ["gte", "lte"] }, { id: "context.maxCompletion", label: "Max Completion Tokens", type: "number", unit: "tokens", operators: ["gte", "lte"] }, { id: "supportedParameters", label: "Supported Parameter", type: "text", operators: ["contains", "exists"] }, { id: "supportsImplicitCaching", label: "Implicit Caching", type: "boolean", operators: ["eq", "exists"] }, { id: "provider.routingId", label: "Provider Routing ID", type: "text", operators: ["eq", "in"] },
] as Field[]);
const pricingLabels: Record<string, string> = { prompt: "Input", completion: "Output", input_cache_read: "Cache Read", input_cache_write: "Cache Write", cache_read: "Cache Read", cache_write: "Cache Write", cache_write_5m: "Cache Write 5m", cache_write_1h: "Cache Write 1h" };
function fieldsFor(endpoints: Endpoint[]): Field[] { const keys = new Set<string>(); endpoints.forEach((endpoint) => Object.entries((endpoint.pricing ?? {}) as Record<string, unknown>).forEach(([key, value]) => { if (typeof value === "number" || (typeof value === "string" && Number.isFinite(Number(value)))) keys.add(key); })); return [...keys].map((key) => ({ id: `pricing.${key}`, label: pricingLabels[key] ?? key.replaceAll("_", " "), type: "number" as const, unit: "$/M", operators: ["lte", "gte"] as FilterOperator[] })); }
function emptyFilter(): ProviderFilterConfig { return { enabled: true, mode: "all", conditions: [], maxTelemetryAgeMs: 1_800_000 }; }
/** The control API answers with `{ filter, preview }`, so the saved config must be unwrapped before use. */
function unwrap(value: ProviderFilterConfig | { providerFilter?: ProviderFilterConfig | null } | { filter?: ProviderFilterConfig | null } | null): ProviderFilterConfig | null {
  if (!value || typeof value !== "object") return null;
  if ("providerFilter" in value) return (value as { providerFilter?: ProviderFilterConfig | null }).providerFilter ?? null;
  if ("filter" in value) return (value as { filter?: ProviderFilterConfig | null }).filter ?? null;
  return value as ProviderFilterConfig;
}

export function DesiredModelDetail({ modelId, models, onBack, setNotice, setError }: { modelId: string; models: ModelSummary[]; onBack: () => void; setNotice: (value: string) => void; setError: (value: string) => void }) {
  const [endpoints, setEndpoints] = useState<Endpoint[]>([]); const [filter, setFilter] = useState(emptyFilter); const [preview, setPreview] = useState<FilterPreview | null>(null); const [busy, setBusy] = useState(true); const [previewing, setPreviewing] = useState(false); const [showExcluded, setShowExcluded] = useState(false); const fields = useMemo(() => fieldsFor(endpoints), [endpoints]);
  useEffect(() => { void Promise.all([api.endpoints(modelId), api.desiredFilter(modelId).catch(() => null)]).then(([result, saved]) => { setEndpoints(result.items); const next = unwrap(saved); if (next) setFilter({ ...next, conditions: next.conditions ?? [] }); }).catch((err: Error) => setError(err.message)).finally(() => setBusy(false)); }, [modelId]);
  useEffect(() => { const timer = window.setTimeout(() => { setPreviewing(true); const candidateFilter = { ...filter, conditions: filter.conditions.filter((condition) => condition.enabled) }; void api.previewDesiredFilter(modelId, candidateFilter).then(setPreview).catch((err: Error) => setError(err.message)).finally(() => setPreviewing(false)); }, 300); return () => window.clearTimeout(timer); }, [modelId, filter]);
  const update = (index: number, patch: Partial<ProviderFilterCondition>) => setFilter((current) => ({ ...current, conditions: current.conditions.map((item, i) => i === index ? { ...item, ...patch } : item) }));
  const save = async () => { try { await api.saveDesiredFilter(modelId, filter); setNotice("Provider Filters saved."); } catch (err) { setError((err as Error).message); } };
  const remove = async () => { try { await api.deleteDesiredFilter(modelId); setFilter(emptyFilter()); setPreview(null); setNotice("Provider Filters removed; all endpoints are eligible."); } catch (err) { setError((err as Error).message); } };
  if (busy) return <section className="page desired-detail"><Breadcrumbs trail={[{ label: "Desired Models", onClick: onBack }, { label: "Loading…" }]} /><p className="muted">Loading Desired Model…</p></section>;
  const model = models.find((item) => item.id === modelId);
  const excluded = preview ? preview.excludedEndpoints : [];
  return <section className="page desired-detail"><Breadcrumbs trail={[{ label: "Desired Models", onClick: onBack }, { label: model?.name || modelId }]} /><div className="page-heading"><div><p className="eyebrow">Desired Model</p><h1>{model?.name || modelId}</h1><code className="mono">{modelId}</code></div><Badge variant={filter.conditions.length ? "accent" : "neutral"}>{filter.conditions.length ? "Filter active" : "No filter"}</Badge></div><div className="filter-layout"><section className="panel"><div className="panel-title"><div><h2>Provider Filters</h2><p>All conditions must pass. These rules are enforced before every routed request.</p></div><label className="switch"><input type="checkbox" checked={filter.enabled} onChange={(event) => setFilter({ ...filter, enabled: event.target.checked })} />Enabled</label></div>{filter.conditions.map((condition, index) => <ConditionRow key={condition.id} condition={condition} index={index} fields={fields} update={update} remove={() => setFilter({ ...filter, conditions: filter.conditions.filter((_, i) => i !== index) })} />)}<button className="button secondary" onClick={() => { const field = fields[0] ?? baseFields[0]; setFilter({ ...filter, conditions: [...filter.conditions, { id: `condition_${Date.now()}`, field: field.id, operator: field.operators[0], value: field.type === "boolean" ? true : "", enabled: true }] }); }}>+ Add condition</button><label className="telemetry-age">Maximum telemetry age (seconds)<input aria-label="Maximum telemetry age" type="number" min="1" value={Number.isFinite(filter.maxTelemetryAgeMs) ? Math.round(filter.maxTelemetryAgeMs / 1000) : ""} onChange={(event) => setFilter({ ...filter, maxTelemetryAgeMs: Math.max(1000, Number(event.target.value) * 1000) })} /><small>Previews and proxy routing reject snapshots older than this value.</small></label><div className="actions"><button className="button" onClick={() => void save()}>Save Filter</button><button className="text-button danger-text" onClick={() => void remove()}>Delete filter</button></div></section><Preview preview={preview} endpointCount={endpoints.length} loading={previewing} showExcluded={showExcluded} onToggleExcluded={() => setShowExcluded(!showExcluded)} excludedCount={excluded.length} /></div></section>;
}

function ConditionRow({ condition, index, fields, update, remove }: { condition: ProviderFilterCondition; index: number; fields: Field[]; update: (index: number, patch: Partial<ProviderFilterCondition>) => void; remove: () => void }) { const field = [...fields, ...baseFields].find((item) => item.id === condition.field) ?? { id: condition.field, label: condition.field, type: "text" as const, operators: ["eq"] as FilterOperator[] }; return <div className="filter-condition"><select aria-label="Filter field" value={condition.field} onChange={(event) => { const next = [...fields, ...baseFields].find((item) => item.id === event.target.value); update(index, { field: event.target.value, operator: next?.operators[0] ?? "eq", value: next?.type === "boolean" }); }}><optgroup label="Pricing">{fields.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</optgroup><optgroup label="Performance, reliability & capabilities">{baseFields.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</optgroup></select><select aria-label="Filter operator" value={condition.operator} onChange={(event) => update(index, { operator: event.target.value as FilterOperator })}>{field.operators.map((operator) => <option key={operator} value={operator}>{({ lte: "≤", gte: "≥", eq: "=", in: "in", contains: "contains", exists: "exists" } as Record<string, string>)[operator]}</option>)}</select>{field.type === "boolean" ? <select aria-label="Filter value" value={String(condition.value)} onChange={(event) => update(index, { value: event.target.value === "true" })}><option value="true">Required</option><option value="false">Not required</option></select> : condition.operator === "exists" ? <span className="muted">present</span> : <input aria-label="Filter value" type={field.type === "number" ? "number" : "text"} value={Array.isArray(condition.value) ? condition.value.join(", ") : String(condition.value ?? "")} onChange={(event) => update(index, { value: field.type === "number" ? (event.target.value === "" ? "" : Number(event.target.value)) : event.target.value })} />}{field.unit && <span className="filter-unit">{field.unit}</span>}<label className="condition-toggle" title="Enable this condition"><input type="checkbox" checked={condition.enabled} onChange={(event) => update(index, { enabled: event.target.checked })} /></label><button className="condition-delete" aria-label={`Delete condition ${index + 1}`} onClick={remove}>✕</button></div>; }

function Preview({ preview, endpointCount, loading, showExcluded, onToggleExcluded, excludedCount }: { preview: FilterPreview | null; endpointCount: number; loading: boolean; showExcluded: boolean; onToggleExcluded: () => void; excludedCount: number }) {
  const fetchedAt = preview?.metadataFetchedAt ?? null;
  const ageMs = fetchedAt ? Date.now() - Date.parse(fetchedAt) : null;
  const age = ageMs !== null && Number.isFinite(ageMs) ? `${Math.max(0, Math.round(ageMs / 1000))}s` : null;
  const state = preview?.metadataState ?? "unavailable";
  const freshness = state === "unavailable" ? { label: "Unavailable", variant: "danger" as const } : state === "stale" ? { label: "Stale", variant: "warning" as const } : { label: "Fresh", variant: "success" as const };
  const rows: Array<{ endpoint: FilterPreviewEndpoint; eligible: boolean; reasons: FilterPreviewReason[] }> = preview ? [...preview.eligibleEndpoints, ...(showExcluded ? preview.excludedEndpoints : [])] : [];
  const total = preview?.totalEndpoints ?? endpointCount;
  const eligible = preview ? preview.eligibleEndpoints.length : null;
  return <section className="panel filter-preview"><div className="panel-title"><div><h2>Live result</h2><p>{loading ? "Evaluating…" : `${total} endpoints → ${eligible ?? "—"} eligible`}</p><span className="freshness"><Badge variant={freshness.variant}>{freshness.label}</Badge><small>{age ? `Telemetry updated ${age} ago` : "Telemetry age unknown"}{fetchedAt ? ` · fetched ${new Date(fetchedAt).toLocaleString()}` : ""}</small></span>{preview?.usable === false && preview.failureReason && <Badge variant="danger">{preview.failureReason}</Badge>}</div></div><div className="table-wrap"><table><thead><tr><th>Provider</th><th>Endpoint</th><th>Result</th><th>Reasons</th></tr></thead><tbody>{!preview ? <tr><td colSpan={4}>Adjust a condition to preview eligibility.</td></tr> : rows.length === 0 ? <tr><td colSpan={4}>No endpoint matches these conditions.</td></tr> : rows.map(({ endpoint, eligible: isEligible, reasons }, index) => <tr key={`${endpoint.providerRoutingId ?? "unknown"}-${index}`} className={isEligible ? "" : "row-excluded"}><td>{endpoint.providerName ?? "Unknown"}</td><td><code className="mono">{endpoint.providerRoutingId ?? "Unavailable"}</code></td><td><Badge variant={isEligible ? "success" : "danger"}>{isEligible ? "Eligible" : "Excluded"}</Badge></td><td>{reasons.length ? reasons.map((reason) => <div key={`${reason.code}-${reason.message}`}>✕ {reason.message}</div>) : "—"}</td></tr>)}</tbody></table></div>{excludedCount > 0 && <button className="button secondary view-excluded" onClick={onToggleExcluded}>{showExcluded ? "Hide excluded" : `View excluded (${excludedCount})`}</button>}</section>;
}
