import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import type { DesiredModel, Endpoint, FilterOperator, FilterPreview, ProviderFilterCondition, ProviderFilterConfig, ModelSummary } from "./types";

type Field = { id: string; label: string; type: "number" | "text" | "boolean"; unit?: string; operators: FilterOperator[] };
const baseFields: Field[] = ["p50", "p75", "p90", "p99"].flatMap((p) => [{ id: `performance.throughput.${p}`, label: `Throughput ${p.toUpperCase()}`, type: "number" as const, unit: "t/s", operators: ["gte", "lte"] as FilterOperator[] }, { id: `performance.latency.${p}`, label: `Latency ${p.toUpperCase()}`, type: "number" as const, unit: "s", operators: ["lte", "gte"] as FilterOperator[] }]).concat([
  ...["5m", "30m", "1d"].map((window) => ({ id: `uptime.${window}`, label: `Uptime ${window}`, type: "number" as const, unit: "%", operators: ["gte", "lte"] as FilterOperator[] })),
  { id: "quantization", label: "Quantization", type: "text", operators: ["eq", "in"] }, { id: "context.length", label: "Context Length", type: "number", unit: "tokens", operators: ["gte", "lte"] }, { id: "context.maxPrompt", label: "Max Prompt Tokens", type: "number", unit: "tokens", operators: ["gte", "lte"] }, { id: "context.maxCompletion", label: "Max Completion Tokens", type: "number", unit: "tokens", operators: ["gte", "lte"] }, { id: "supportedParameters", label: "Supported Parameter", type: "text", operators: ["contains", "exists"] }, { id: "supportsImplicitCaching", label: "Implicit Caching", type: "boolean", operators: ["eq", "exists"] }, { id: "provider.routingId", label: "Provider Routing ID", type: "text", operators: ["eq", "in"] },
] as Field[]);
const pricingLabels: Record<string, string> = { prompt: "Input", completion: "Output", input_cache_read: "Cache Read", input_cache_write: "Cache Write", cache_read: "Cache Read", cache_write: "Cache Write", cache_write_5m: "Cache Write 5m", cache_write_1h: "Cache Write 1h" };
function fieldsFor(endpoints: Endpoint[]): Field[] { const keys = new Set<string>(); endpoints.forEach((endpoint) => Object.entries((endpoint.pricing ?? {}) as Record<string, unknown>).forEach(([key, value]) => { if (typeof value === "number" || (typeof value === "string" && Number.isFinite(Number(value)))) keys.add(key); })); return [...keys].map((key) => ({ id: `pricing.${key}`, label: pricingLabels[key] ?? key.replaceAll("_", " "), type: "number" as const, unit: "$/M", operators: ["lte", "gte"] as FilterOperator[] })); }
function emptyFilter(): ProviderFilterConfig { return { enabled: true, mode: "all", conditions: [], maxTelemetryAgeMs: 1_800_000 }; }
function unwrap(value: ProviderFilterConfig | { providerFilter?: ProviderFilterConfig | null } | null): ProviderFilterConfig | null { return value && "providerFilter" in value ? value.providerFilter ?? null : value; }

export function DesiredModelDetail({ modelId, models, onBack, setNotice, setError }: { modelId: string; models: ModelSummary[]; onBack: () => void; setNotice: (value: string) => void; setError: (value: string) => void }) {
  const [endpoints, setEndpoints] = useState<Endpoint[]>([]); const [filter, setFilter] = useState(emptyFilter); const [preview, setPreview] = useState<FilterPreview | null>(null); const [busy, setBusy] = useState(true); const [previewing, setPreviewing] = useState(false); const fields = useMemo(() => fieldsFor(endpoints), [endpoints]);
  useEffect(() => { void Promise.all([api.endpoints(modelId), api.desiredFilter(modelId).catch(() => null)]).then(([result, saved]) => { setEndpoints(result.items); const next = unwrap(saved); if (next) setFilter({ ...next, conditions: next.conditions ?? [] }); }).catch((err: Error) => setError(err.message)).finally(() => setBusy(false)); }, [modelId]);
  useEffect(() => { const timer = window.setTimeout(() => { setPreviewing(true); void api.previewDesiredFilter(modelId, filter.conditions.filter((condition) => condition.enabled)).then(setPreview).catch((err: Error) => setError(err.message)).finally(() => setPreviewing(false)); }, 300); return () => window.clearTimeout(timer); }, [modelId, filter.conditions]);
  const update = (index: number, patch: Partial<ProviderFilterCondition>) => setFilter((current) => ({ ...current, conditions: current.conditions.map((item, i) => i === index ? { ...item, ...patch } : item) }));
  const save = async () => { try { await api.saveDesiredFilter(modelId, filter); setNotice("Provider filter saved."); } catch (err) { setError((err as Error).message); } };
  const remove = async () => { try { await api.deleteDesiredFilter(modelId); setFilter(emptyFilter()); setPreview(null); setNotice("Provider filter removed; all endpoints are eligible."); } catch (err) { setError((err as Error).message); } };
  if (busy) return <section className="page">Loading Desired Model…</section>;
  const model = models.find((item) => item.id === modelId);
  return <section className="page desired-detail"><button className="back" onClick={onBack}>← Desired Models</button><div className="page-heading"><div><p className="eyebrow">Desired Model</p><h1>{model?.name || modelId}</h1><code>{modelId}</code></div><span className={filter.conditions.length ? "status good" : "status"}>{filter.conditions.length ? "Filter active" : "No filter"}</span></div><div className="filter-layout"><section className="panel"><div className="panel-title"><div><h2>Hard Provider Filters</h2><p>All conditions must pass. Missing data excludes the endpoint.</p></div><label className="switch"><input type="checkbox" checked={filter.enabled} onChange={(event) => setFilter({ ...filter, enabled: event.target.checked })} />Enabled</label></div>{filter.conditions.map((condition, index) => <ConditionRow key={condition.id} condition={condition} index={index} fields={fields} update={update} remove={() => setFilter({ ...filter, conditions: filter.conditions.filter((_, i) => i !== index) })} />)}<button className="button secondary" onClick={() => { const field = fields[0] ?? baseFields[0]; setFilter({ ...filter, conditions: [...filter.conditions, { id: `condition_${Date.now()}`, field: field.id, operator: field.operators[0], value: field.type === "boolean" ? true : "", enabled: true }] }); }}>+ Add condition</button><div className="actions"><button className="button" onClick={() => void save()}>Save Filter</button><button className="text-button danger-text" onClick={() => void remove()}>Delete filter</button></div></section><Preview preview={preview} endpointCount={endpoints.length} loading={previewing} /></div></section>;
}

function ConditionRow({ condition, index, fields, update, remove }: { condition: ProviderFilterCondition; index: number; fields: Field[]; update: (index: number, patch: Partial<ProviderFilterCondition>) => void; remove: () => void }) { const field = [...fields, ...baseFields].find((item) => item.id === condition.field) ?? { id: condition.field, label: condition.field, type: "text" as const, operators: ["eq"] as FilterOperator[] }; return <div className="filter-condition"><select aria-label="Filter field" value={condition.field} onChange={(event) => { const next = [...fields, ...baseFields].find((item) => item.id === event.target.value); update(index, { field: event.target.value, operator: next?.operators[0] ?? "eq", value: next?.type === "boolean" }); }}><optgroup label="Pricing">{fields.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</optgroup><optgroup label="Performance, reliability & capabilities">{baseFields.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</optgroup></select><select aria-label="Filter operator" value={condition.operator} onChange={(event) => update(index, { operator: event.target.value as FilterOperator })}>{field.operators.map((operator) => <option key={operator} value={operator}>{({ lte: "≤", gte: "≥", eq: "=", in: "in", contains: "contains", exists: "exists" } as Record<string, string>)[operator]}</option>)}</select>{field.type === "boolean" ? <select aria-label="Filter value" value={String(condition.value)} onChange={(event) => update(index, { value: event.target.value === "true" })}><option value="true">Required</option><option value="false">Not required</option></select> : condition.operator === "exists" ? <span className="muted">present</span> : <input aria-label="Filter value" type={field.type === "number" ? "number" : "text"} value={Array.isArray(condition.value) ? condition.value.join(", ") : String(condition.value ?? "")} onChange={(event) => update(index, { value: field.type === "number" ? Number(event.target.value) : condition.operator === "in" ? event.target.value.split(",").map((part) => part.trim()).filter(Boolean) : event.target.value })} placeholder="Value" />}<span className="filter-unit">{field.unit ?? ""}</span><button className="text-button" aria-label="Remove condition" onClick={remove}>×</button></div>; }
function Preview({ preview, endpointCount, loading }: { preview: FilterPreview | null; endpointCount: number; loading: boolean }) { return <section className="panel filter-preview"><div className="panel-title"><div><h2>Eligibility preview</h2><p>{loading ? "Evaluating…" : `${preview?.total ?? endpointCount} endpoints → ${preview?.eligible ?? (preview ? 0 : "—")} eligible`}</p></div></div><div className="table-wrap"><table><thead><tr><th>Provider</th><th>Endpoint</th><th>Result</th><th>Reasons</th></tr></thead><tbody>{!preview ? <tr><td colSpan={4}>Adjust a condition to preview eligibility.</td></tr> : preview.endpoints.map((endpoint, index) => <tr key={`${endpoint.providerRoutingId ?? "unknown"}-${index}`}><td>{endpoint.providerName ?? "Unknown"}</td><td><code>{endpoint.providerRoutingId ?? "Unavailable"}</code></td><td><span className={endpoint.eligible ? "status good" : "status bad"}>{endpoint.eligible ? "Eligible" : "Excluded"}</span></td><td>{endpoint.reasons.length ? endpoint.reasons.map((reason) => <div key={`${reason.code}-${reason.message}`}>{reason.message}</div>) : "—"}</td></tr>)}</tbody></table></div></section>; }
