import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../api";
import { Badge, EmptyState, PageHeader } from "../components";
import type { CatalogCache, DesiredModel, ModelSummary } from "../types";

type Sort = "default" | "newest" | "input" | "output" | "context" | "az";
type State = { query: string; creator: string; modality: string; context: number; maxInput: string; maxOutput: string; free: boolean; capability: string; sort: Sort; page: number };
const PAGE_SIZE = 50;
const sorts: Sort[] = ["default", "newest", "input", "output", "context", "az"];
const price = (model: ModelSummary, key: "prompt" | "completion") => { const raw = model.pricing && typeof model.pricing === "object" ? (model.pricing as Record<string, unknown>)[key] : null; const parsed = typeof raw === "string" ? Number(raw) : raw; return typeof parsed === "number" && Number.isFinite(parsed) ? parsed * 1_000_000 : null; };
const money = (number: number | null) => number === null ? "—" : number === 0 ? "Free" : `$${number.toLocaleString(undefined, { maximumFractionDigits: 4 })} / M`;
const compact = (tokens: number | null) => !tokens ? "—" : tokens >= 1_000_000 ? `${(tokens / 1_000_000).toFixed(tokens % 1_000_000 ? 1 : 0)}M` : `${Math.round(tokens / 1_000)}K`;
const validNumber = (value: string | null) => value && /^\d+$/.test(value) ? Number(value) : 0;
function fromUrl(): State { const p = new URLSearchParams(window.location.search); const sort = p.get("sort") as Sort; return { query: p.get("q") ?? "", creator: p.get("creator") ?? "", modality: p.get("modality") ?? "", context: validNumber(p.get("context")), maxInput: p.get("maxInputPrice") ?? "", maxOutput: p.get("maxOutputPrice") ?? "", free: p.get("free") === "1", capability: p.get("capability") ?? "", sort: sorts.includes(sort) ? sort : "default", page: Math.max(0, validNumber(p.get("page")) - 1) }; }
function toUrl(state: State): string { const p = new URLSearchParams(); if (state.query) p.set("q", state.query); if (state.creator) p.set("creator", state.creator); if (state.modality) p.set("modality", state.modality); if (state.context) p.set("context", String(state.context)); if (state.maxInput) p.set("maxInputPrice", state.maxInput); if (state.maxOutput) p.set("maxOutputPrice", state.maxOutput); if (state.free) p.set("free", "1"); if (state.capability) p.set("capability", state.capability); if (state.sort !== "default") p.set("sort", state.sort); p.set("page", String(state.page + 1)); return `${window.location.pathname}?${p}`; }
function capabilities(model: ModelSummary): string[] { const fields = new Set((model.supportedParameters ?? []).map((item) => item.toLowerCase())); const badges: string[] = []; if (["tools", "tool_choice", "tool_calls"].some((item) => fields.has(item))) badges.push("Tools"); if (["response_format", "structured_outputs", "json_schema"].some((item) => fields.has(item))) badges.push("Structured Output"); if (["reasoning", "reasoning_effort"].some((item) => fields.has(item))) badges.push("Reasoning"); if ((model.inputModalities ?? []).some((item) => ["image", "video"].includes(item.toLowerCase()))) badges.push("Vision"); return badges; }
const emptyState: State = { query: "", creator: "", modality: "", context: 0, maxInput: "", maxOutput: "", free: false, capability: "", sort: "default", page: 0 };
const activeFilters = (state: State) => [state.query && "Search", state.creator && "Creator", state.modality && "Modality", state.context && "Context", state.maxInput && "Max input", state.maxOutput && "Max output", state.free && "Free only", state.capability && "Capability"].filter(Boolean) as string[];

export function AllModelsPage({ models, desired, cache, refreshModels, onOpen, onDesiredChange, setError }: { models: ModelSummary[]; desired: DesiredModel[]; cache: CatalogCache | null; refreshModels: () => Promise<void>; onOpen: (id: string) => void; onDesiredChange: () => void; setError: (value: string) => void }) {
  const [state, setState] = useState<State>(fromUrl);
  const [advanced, setAdvanced] = useState(false);
  const update = useCallback((next: Partial<State>, resetPage = true) => setState((current) => { const value = { ...current, ...next, ...(resetPage ? { page: 0 } : {}) }; window.history.pushState(null, "", toUrl(value)); return value; }), []);
  useEffect(() => { const restore = () => setState(fromUrl()); window.addEventListener("popstate", restore); return () => window.removeEventListener("popstate", restore); }, []);
  const desiredIds = useMemo(() => new Set(desired.map((item) => item.modelId)), [desired]);
  const creators = useMemo(() => [...new Set(models.map((model) => model.creator).filter((item): item is string => Boolean(item)))].sort(), [models]);
  const filtered = useMemo(() => models.filter((model) => { const text = `${model.id} ${model.name ?? ""} ${model.creator ?? ""} ${model.description ?? ""}`.toLowerCase(); const input = price(model, "prompt"); const output = price(model, "completion"); return (!state.query || text.includes(state.query.toLowerCase())) && (!state.creator || model.creator === state.creator) && (!state.modality || (model.inputModalities ?? []).some((item) => item.toLowerCase() === state.modality)) && (!state.context || (model.contextLength ?? 0) >= state.context) && (!state.maxInput || (input !== null && input <= Number(state.maxInput))) && (!state.maxOutput || (output !== null && output <= Number(state.maxOutput))) && (!state.free || (input === 0 && output === 0)) && (!state.capability || capabilities(model).includes(state.capability)); }).sort((a, b) => { const numeric = (left: number | null, right: number | null, desc = false) => ((left ?? (desc ? -Infinity : Infinity)) - (right ?? (desc ? -Infinity : Infinity))) * (desc ? -1 : 1); if (state.sort === "newest") return numeric(a.created ?? null, b.created ?? null, true) || a.id.localeCompare(b.id); if (state.sort === "input") return numeric(price(a, "prompt"), price(b, "prompt")) || a.id.localeCompare(b.id); if (state.sort === "output") return numeric(price(a, "completion"), price(b, "completion")) || a.id.localeCompare(b.id); if (state.sort === "context") return numeric(a.contextLength, b.contextLength, true) || a.id.localeCompare(b.id); return `${a.name ?? a.id}`.localeCompare(`${b.name ?? b.id}`) || a.id.localeCompare(b.id); }), [models, state]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const page = Math.min(state.page, pageCount - 1); const visible = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const chips = activeFilters(state);
  const toggle = async (id: string) => { try { if (desiredIds.has(id)) { if (!window.confirm("Remove this Desired Model? This immediately revokes it from API Keys and removes its per-key provider overrides.")) return; await api.removeDesiredModel(id); } else await api.addDesiredModel(id); onDesiredChange(); } catch (error) { setError((error as Error).message); } };
  return <section className="page page-wide"><PageHeader eyebrow="Catalog" title="All Models" description="Browse the OpenRouter catalog and add models to your Desired Models pool." actions={<button className="button secondary" onClick={() => void refreshModels()}>Refresh catalog</button>} />
    {cache?.stale && <div className="catalog-state" role="status">Showing a stale local snapshot from {cache.fetchedAt ? new Date(cache.fetchedAt).toLocaleString() : "an unknown time"}.</div>}
    <div className="catalog-controls"><input aria-label="Search models" value={state.query} onChange={(event) => update({ query: event.target.value })} placeholder="Search ID, name, creator, or description" /><select aria-label="Creator" value={state.creator} onChange={(event) => update({ creator: event.target.value })}><option value="">All creators</option>{creators.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Modality" value={state.modality} onChange={(event) => update({ modality: event.target.value })}><option value="">All modalities</option><option value="text">Text</option><option value="image">Image</option><option value="audio">Audio</option><option value="video">Video</option></select><select aria-label="Context length" value={state.context} onChange={(event) => update({ context: Number(event.target.value) })}><option value="0">Any context</option><option value="32000">≥ 32K</option><option value="64000">≥ 64K</option><option value="128000">≥ 128K</option><option value="256000">≥ 256K</option><option value="1000000">≥ 1M</option></select><select aria-label="Sort models" value={state.sort} onChange={(event) => update({ sort: event.target.value as Sort })}><option value="default">Default</option><option value="newest">Newest</option><option value="input">Lowest input price</option><option value="output">Lowest output price</option><option value="context">Largest context</option><option value="az">A–Z</option></select><button className="button secondary more-filters" aria-expanded={advanced} onClick={() => setAdvanced(!advanced)}>{advanced ? "Fewer filters" : "More filters"}</button></div>
    {advanced && <div className="catalog-controls catalog-controls-advanced"><input aria-label="Maximum input price per million" type="number" min="0" value={state.maxInput} onChange={(event) => update({ maxInput: event.target.value })} placeholder="Max input $/M" /><input aria-label="Maximum output price per million" type="number" min="0" value={state.maxOutput} onChange={(event) => update({ maxOutput: event.target.value })} placeholder="Max output $/M" /><select aria-label="Capability" value={state.capability} onChange={(event) => update({ capability: event.target.value })}><option value="">All capabilities</option><option>Tools</option><option>Structured Output</option><option>Reasoning</option><option>Vision</option></select><label className="catalog-checkbox"><input type="checkbox" checked={state.free} onChange={(event) => update({ free: event.target.checked })} />Free only</label></div>}
    {chips.length > 0 && <div className="filter-chips" role="status"><Badge variant="accent">{chips.length} {chips.length === 1 ? "filter" : "filters"}</Badge>{chips.map((chip) => <span className="chip" key={chip}>{chip}</span>)}<button className="text-button" onClick={() => update({ ...emptyState })}>Clear</button></div>}
    {!cache?.available && models.length === 0 ? <EmptyState title="No cached models yet" description="Configure an OpenRouter key outside the UI, then refresh the catalog." action={<button className="button secondary" onClick={() => void refreshModels()}>Refresh catalog</button>} /> : <><p className="catalog-count">{filtered.length} of {models.length} models · page {page + 1} of {pageCount}</p><div className="model-list catalog-list">{visible.length === 0 ? <EmptyState title="No models match these filters" description="Clear one or more filters to broaden the local catalog." action={<button className="button secondary" onClick={() => update({ ...emptyState })}>Clear filters</button>} /> : visible.map((model) => <article className="model-row catalog-row" key={model.id}><button className="model-link" onClick={() => onOpen(model.id)}><strong>{model.name || model.id}</strong><small className="mono">{model.creator ?? "Unknown creator"} · {model.id}</small><span className="catalog-inline"><span>{compact(model.contextLength)} context</span><span>In {money(price(model, "prompt"))}</span><span>Out {money(price(model, "completion"))}</span></span><span className="catalog-badges">{(model.inputModalities ?? []).slice(0, 3).map((item) => <i key={item}>{item}</i>)}{capabilities(model).map((item) => <i key={item}>{item}</i>)}</span></button><span className="model-meta"><button className={desiredIds.has(model.id) ? "desired-button selected" : "desired-button"} onClick={() => void toggle(model.id)}>{desiredIds.has(model.id) ? "✓ Desired" : "Add to Desired"}</button></span></article>)}</div><div className="catalog-pagination"><button className="button secondary" disabled={page === 0} onClick={() => update({ page: page - 1 }, false)}>Previous</button><button className="button secondary" disabled={page + 1 >= pageCount} onClick={() => update({ page: page + 1 }, false)}>Next</button></div></>}
  </section>;
}
