import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../api";
import { Badge, EmptyState, PageHeader } from "../components";
import { modelRelevance } from "../search";
import { useI18n } from "../i18n";
import type { CatalogCache, DesiredModel, ModelSummary } from "../types";

type Sort = "default" | "newest" | "input" | "output" | "context" | "az";
type State = { query: string; creator: string; modality: string; context: number; maxInput: string; maxOutput: string; free: boolean; capability: string; sort: Sort; page: number };
const PAGE_SIZE = 50;
const sorts: Sort[] = ["default", "newest", "input", "output", "context", "az"];
const price = (model: ModelSummary, key: "prompt" | "completion") => { const raw = model.pricing && typeof model.pricing === "object" ? (model.pricing as Record<string, unknown>)[key] : null; const parsed = typeof raw === "string" ? Number(raw) : raw; return typeof parsed === "number" && Number.isFinite(parsed) ? parsed * 1_000_000 : null; };
const money = (number: number | null, freeLabel: string) => number === null ? "—" : number === 0 ? freeLabel : `$${number.toLocaleString(undefined, { maximumFractionDigits: 4 })} / M`;
const compact = (tokens: number | null) => !tokens ? "—" : tokens >= 1_000_000 ? `${(tokens / 1_000_000).toFixed(tokens % 1_000_000 ? 1 : 0)}M` : `${Math.round(tokens / 1_000)}K`;
const validNumber = (value: string | null) => value && /^\d+$/.test(value) ? Number(value) : 0;
function fromUrl(): State { const p = new URLSearchParams(window.location.search); const sort = p.get("sort") as Sort; return { query: p.get("q") ?? "", creator: p.get("creator") ?? "", modality: p.get("modality") ?? "", context: validNumber(p.get("context")), maxInput: p.get("maxInputPrice") ?? "", maxOutput: p.get("maxOutputPrice") ?? "", free: p.get("free") === "1", capability: p.get("capability") ?? "", sort: sorts.includes(sort) ? sort : "default", page: Math.max(0, validNumber(p.get("page")) - 1) }; }
function toUrl(state: State): string { const p = new URLSearchParams(); if (state.query) p.set("q", state.query); if (state.creator) p.set("creator", state.creator); if (state.modality) p.set("modality", state.modality); if (state.context) p.set("context", String(state.context)); if (state.maxInput) p.set("maxInputPrice", state.maxInput); if (state.maxOutput) p.set("maxOutputPrice", state.maxOutput); if (state.free) p.set("free", "1"); if (state.capability) p.set("capability", state.capability); if (state.sort !== "default") p.set("sort", state.sort); p.set("page", String(state.page + 1)); return `${window.location.pathname}?${p}`; }
function capabilities(model: ModelSummary): string[] { const fields = new Set((model.supportedParameters ?? []).map((item) => item.toLowerCase())); const badges: string[] = []; if (["tools", "tool_choice", "tool_calls"].some((item) => fields.has(item))) badges.push("Tools"); if (["response_format", "structured_outputs", "json_schema"].some((item) => fields.has(item))) badges.push("Structured Output"); if (["reasoning", "reasoning_effort"].some((item) => fields.has(item))) badges.push("Reasoning"); if ((model.inputModalities ?? []).some((item) => ["image", "video"].includes(item.toLowerCase()))) badges.push("Vision"); return badges; }
const emptyState: State = { query: "", creator: "", modality: "", context: 0, maxInput: "", maxOutput: "", free: false, capability: "", sort: "default", page: 0 };
export function AllModelsPage({ models, desired, cache, refreshModels, onOpen, onDesiredChange, setError }: { models: ModelSummary[]; desired: DesiredModel[]; cache: CatalogCache | null; refreshModels: () => Promise<void>; onOpen: (id: string) => void; onDesiredChange: () => void; setError: (value: string) => void }) {
  const { t, formatDate } = useI18n();
  const [state, setState] = useState<State>(fromUrl);
  const [advanced, setAdvanced] = useState(false);
  const update = useCallback((next: Partial<State>, resetPage = true) => setState((current) => { const value = { ...current, ...next, ...(resetPage ? { page: 0 } : {}) }; window.history.pushState(null, "", toUrl(value)); return value; }), []);
  useEffect(() => { const restore = () => setState(fromUrl()); window.addEventListener("popstate", restore); return () => window.removeEventListener("popstate", restore); }, []);
  const desiredIds = useMemo(() => new Set(desired.map((item) => item.modelId)), [desired]);
  const creators = useMemo(() => [...new Set(models.map((model) => model.creator).filter((item): item is string => Boolean(item)))].sort(), [models]);
  const filtered = useMemo(() => {
    const numeric = (left: number | null, right: number | null, desc = false) => ((left ?? (desc ? -Infinity : Infinity)) - (right ?? (desc ? -Infinity : Infinity))) * (desc ? -1 : 1);
    const selectedSort = (a: ModelSummary, b: ModelSummary) => {
      if (state.sort === "newest") return numeric(a.created ?? null, b.created ?? null, true) || a.id.localeCompare(b.id);
      if (state.sort === "input") return numeric(price(a, "prompt"), price(b, "prompt")) || a.id.localeCompare(b.id);
      if (state.sort === "output") return numeric(price(a, "completion"), price(b, "completion")) || a.id.localeCompare(b.id);
      if (state.sort === "context") return numeric(a.contextLength, b.contextLength, true) || a.id.localeCompare(b.id);
      return `${a.name ?? a.id}`.localeCompare(`${b.name ?? b.id}`) || a.id.localeCompare(b.id);
    };
    return models.filter((model) => {
      const input = price(model, "prompt"); const output = price(model, "completion");
      return (!state.query || modelRelevance(model, state.query) !== null) && (!state.creator || model.creator === state.creator) && (!state.modality || (model.inputModalities ?? []).some((item) => item.toLowerCase() === state.modality)) && (!state.context || (model.contextLength ?? 0) >= state.context) && (!state.maxInput || (input !== null && input <= Number(state.maxInput))) && (!state.maxOutput || (output !== null && output <= Number(state.maxOutput))) && (!state.free || (input === 0 && output === 0)) && (!state.capability || capabilities(model).includes(state.capability));
    }).sort((a, b) => state.query ? (modelRelevance(b, state.query) ?? -Infinity) - (modelRelevance(a, state.query) ?? -Infinity) || selectedSort(a, b) : selectedSort(a, b));
  }, [models, state]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const page = Math.min(state.page, pageCount - 1); const visible = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  const chips = [state.query && t("catalog.searchFilter"), state.creator && t("catalog.creatorFilter"), state.modality && t("catalog.modalityFilter"), state.context && t("catalog.contextFilter"), state.maxInput && t("catalog.maxInputFilter"), state.maxOutput && t("catalog.maxOutputFilter"), state.free && t("catalog.freeFilter"), state.capability && t("catalog.capabilityFilter")].filter(Boolean) as string[];
  const capabilityLabel = (value: string) => value === "Tools" ? t("catalog.tools") : value === "Structured Output" ? t("catalog.structuredOutput") : value === "Reasoning" ? t("catalog.reasoning") : value === "Vision" ? t("catalog.vision") : value;
  const toggle = async (id: string) => { try { if (desiredIds.has(id)) { if (!window.confirm(t("desired.confirmRemove", { model: id }))) return; await api.removeDesiredModel(id); } else await api.addDesiredModel(id); onDesiredChange(); } catch (error) { setError((error as Error).message); } };
  return <section className="page page-wide"><PageHeader eyebrow={t("catalog.eyebrow")} title={t("catalog.title")} description={t("catalog.description")} actions={<button className="button secondary" onClick={() => void refreshModels()}>{t("catalog.refresh")}</button>} />
    {cache?.stale && <div className="catalog-state" role="status">{t("status.staleSnapshot", { date: cache.fetchedAt ? formatDate(cache.fetchedAt) : t("common.unknown") })}</div>}
    <div className="catalog-controls"><input aria-label={t("catalog.searchModels")} value={state.query} onChange={(event) => update({ query: event.target.value })} placeholder={t("catalog.search")} /><select aria-label={t("catalog.creator")} value={state.creator} onChange={(event) => update({ creator: event.target.value })}><option value="">{t("catalog.allCreators")}</option>{creators.map((item) => <option key={item}>{item}</option>)}</select><select aria-label={t("catalog.modality")} value={state.modality} onChange={(event) => update({ modality: event.target.value })}><option value="">{t("catalog.allModalities")}</option><option value="text">Text</option><option value="image">Image</option><option value="audio">Audio</option><option value="video">Video</option></select><select aria-label={t("catalog.contextLength")} value={state.context} onChange={(event) => update({ context: Number(event.target.value) })}><option value="0">{t("catalog.anyContext")}</option>{[32000, 64000, 128000, 256000, 1000000].map((value) => <option key={value} value={value}>{t("catalog.threshold", { value: value >= 1000000 ? `${value / 1000000}M` : `${value / 1000}K` })}</option>)}</select><select aria-label={t("catalog.sort")} value={state.sort} onChange={(event) => update({ sort: event.target.value as Sort })}><option value="default">{t("catalog.default")}</option><option value="newest">{t("catalog.newest")}</option><option value="input">{t("catalog.lowestInput")}</option><option value="output">{t("catalog.lowestOutput")}</option><option value="context">{t("catalog.largestContext")}</option><option value="az">{t("catalog.az")}</option></select><button className="button secondary more-filters" aria-expanded={advanced} onClick={() => setAdvanced(!advanced)}>{advanced ? t("catalog.fewerFilters") : t("catalog.moreFilters")}</button></div>
    {advanced && <div className="catalog-controls catalog-controls-advanced"><input aria-label={t("catalog.maxInputAria")} type="number" min="0" value={state.maxInput} onChange={(event) => update({ maxInput: event.target.value })} placeholder={t("catalog.maxInput")} /><input aria-label={t("catalog.maxOutputAria")} type="number" min="0" value={state.maxOutput} onChange={(event) => update({ maxOutput: event.target.value })} placeholder={t("catalog.maxOutput")} /><select aria-label={t("catalog.capability")} value={state.capability} onChange={(event) => update({ capability: event.target.value })}><option value="">{t("catalog.allCapabilities")}</option><option>Tools</option><option>Structured Output</option><option>Reasoning</option><option>Vision</option></select><label className="catalog-checkbox"><input type="checkbox" checked={state.free} onChange={(event) => update({ free: event.target.checked })} />{t("catalog.freeOnly")}</label></div>}
    {chips.length > 0 && <div className="filter-chips" role="status"><Badge variant="accent">{chips.length} {chips.length === 1 ? t("catalog.filter") : t("catalog.filters")}</Badge>{chips.map((chip) => <span className="chip" key={chip}>{chip}</span>)}<button className="text-button" onClick={() => update({ ...emptyState })}>{t("catalog.clear")}</button></div>}
    {!cache?.available && models.length === 0 ? <EmptyState title={t("catalog.noCache")} description={t("catalog.configureKey")} action={<button className="button secondary" onClick={() => void refreshModels()}>{t("catalog.refresh")}</button>} /> : <><p className="catalog-count">{t("catalog.modelsCount", { filtered: filtered.length, total: models.length, page: page + 1, pages: pageCount })}</p><div className="model-list catalog-list">{visible.length === 0 ? <EmptyState title={t("catalog.noMatch")} description={t("catalog.broaden")} action={<button className="button secondary" onClick={() => update({ ...emptyState })}>{t("catalog.clearFilters")}</button>} /> : visible.map((model) => <article className="model-row catalog-row" key={model.id}><button className="model-link" onClick={() => onOpen(model.id)}><strong>{model.name || model.id}</strong><small className="mono">{model.creator ?? t("catalog.creatorUnknown")} · {model.id}</small><span className="catalog-inline"><span>{compact(model.contextLength)} {t("catalog.context")}</span><span>{t("catalog.priceIn")} {money(price(model, "prompt"), t("catalog.free"))}</span><span>{t("catalog.priceOut")} {money(price(model, "completion"), t("catalog.free"))}</span></span><span className="catalog-badges">{(model.inputModalities ?? []).slice(0, 3).map((item) => <i key={item}>{item}</i>)}{capabilities(model).map((item) => <i key={item}>{capabilityLabel(item)}</i>)}</span></button><span className="model-meta"><button className={desiredIds.has(model.id) ? "desired-button selected" : "desired-button"} onClick={() => void toggle(model.id)}>{desiredIds.has(model.id) ? t("catalog.desired") : t("catalog.add")}</button></span></article>)}</div><div className="catalog-pagination"><button className="button secondary" disabled={page === 0} onClick={() => update({ page: page - 1 }, false)}>{t("catalog.previous")}</button><button className="button secondary" disabled={page + 1 >= pageCount} onClick={() => update({ page: page + 1 }, false)}>{t("catalog.next")}</button></div></>}
  </section>;
}
