import { useEffect, useState } from "react";
import { AccessKeyRouting } from "../AccessKeyRouting";
import { api } from "../api";
import { Badge, EmptyState, PageHeader } from "../components";
import type { AccessKey, AccessKeySecret, DesiredModel } from "../types";

export function ApiKeysPage({ desired, setNotice, setError }: { desired: DesiredModel[]; setNotice: (value: string) => void; setError: (value: string) => void }) {
  const [keys, setKeys] = useState<AccessKey[]>([]); const [editing, setEditing] = useState<AccessKey | null>(null); const [routingKey, setRoutingKey] = useState<AccessKey | null>(null); const [showForm, setShowForm] = useState(false); const [secret, setSecret] = useState<AccessKeySecret | null>(null);
  const load = async () => { try { const result = await api.accessKeys(); setKeys(Array.isArray(result) ? result : result.items); } catch (err) { setError((err as Error).message); } };
  useEffect(() => { void load(); }, []);
  const save = async (name: string, allowedModels: string[], enabled: boolean) => { try { if (editing) await api.updateAccessKey(editing.id, { name, allowedModels, enabled }); else setSecret(await api.createAccessKey({ name, allowedModels })); setShowForm(false); setEditing(null); await load(); setNotice(editing ? "API Key updated." : "API Key created."); } catch (err) { setError((err as Error).message); } };
  const toggle = async (item: AccessKey) => { try { await api.updateAccessKey(item.id, { enabled: !item.enabled }); await load(); } catch (err) { setError((err as Error).message); } };
  const remove = async (item: AccessKey) => { if (!window.confirm(`Delete API Key "${item.name}"? Clients using this key will immediately lose access.`)) return; try { await api.deleteAccessKey(item.id); await load(); setNotice("API Key deleted."); } catch (err) { setError((err as Error).message); } };
  return <section className="page"><PageHeader eyebrow="Managed gateway" title="API Keys" description="Local keys for /v1/* endpoints. Each key only reaches the models in your Desired Models pool." actions={<button className="button" onClick={() => { setEditing(null); setShowForm(true); }}>Create API Key</button>} />
    {keys.length === 0 ? <EmptyState title="No API Keys" description="Create a local key for Codex, Claude Code, OpenCode, or another client." action={<button className="button" onClick={() => { setEditing(null); setShowForm(true); }}>Create API Key</button>} /> : <div className="panel table-wrap"><table><thead><tr><th>Name</th><th>Key</th><th className="num">Models</th><th>Last used</th><th>Status</th><th /></tr></thead><tbody>{keys.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td><code className="mono">{item.keyPrefix}••••{item.keyLast4}</code></td><td className="num">{item.allowedModels.length} {item.allowedModels.length === 1 ? "model" : "models"}</td><td>{item.lastUsedAt ? new Date(item.lastUsedAt).toLocaleString() : "Never"}</td><td><Badge variant={item.enabled ? "success" : "neutral"}>{item.enabled ? "Enabled" : "Disabled"}</Badge></td><td className="table-actions"><button onClick={() => setRoutingKey(item)}>Provider Access</button><button onClick={() => { setEditing(item); setShowForm(true); }}>Edit</button><button onClick={() => void toggle(item)}>{item.enabled ? "Disable" : "Enable"}</button><button onClick={() => void remove(item)}>Delete</button></td></tr>)}</tbody></table></div>}
    {showForm && <AccessKeyForm initial={editing} desired={desired} onCancel={() => { setShowForm(false); setEditing(null); }} onSave={save} />}{secret && <SecretModal value={secret} onClose={() => setSecret(null)} />}{routingKey && <AccessKeyRouting keyId={routingKey.id} allowedModels={routingKey.allowedModels} onClose={() => setRoutingKey(null)} onSaved={() => void load()} setNotice={setNotice} setError={setError} />}
  </section>;
}

function AccessKeyForm({ initial, desired, onCancel, onSave }: { initial: AccessKey | null; desired: DesiredModel[]; onCancel: () => void; onSave: (name: string, models: string[], enabled: boolean) => void }) {
  const [name, setName] = useState(initial?.name ?? ""); const [selected, setSelected] = useState(initial?.allowedModels ?? []);
  const toggle = (id: string) => setSelected(selected.includes(id) ? selected.filter((value) => value !== id) : [...selected, id]);
  return <div className="modal-backdrop"><section className="modal panel" role="dialog" aria-label={initial ? "Edit API Key" : "Create API Key"}><div className="panel-title"><div><h2>{initial ? "Edit API Key" : "Create API Key"}</h2><p>Allowed Models are chosen from your Desired Models.</p></div><button className="text-button" onClick={onCancel}>Close</button></div><label className="modal-field">Name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Codex" /></label><fieldset className="model-checks"><legend>Allowed Models</legend>{desired.length === 0 ? <p className="muted">Add Desired Models before assigning this key.</p> : desired.map((item) => <label key={item.modelId}><input type="checkbox" checked={selected.includes(item.modelId)} onChange={() => toggle(item.modelId)} />{item.modelId}</label>)}</fieldset><div className="actions"><button className="button secondary" onClick={onCancel}>Cancel</button><button className="button" disabled={!name.trim() || selected.length === 0} onClick={() => onSave(name.trim(), selected, initial?.enabled ?? true)}>{initial ? "Save" : "Create key"}</button></div></section></div>;
}

function SecretModal({ value, onClose }: { value: AccessKeySecret; onClose: () => void }) {
  const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard?.writeText(value.secret); setCopied(true); };
  return <div className="modal-backdrop"><section className="modal panel secret-modal" role="dialog" aria-label="Your API Key"><h2>Your API Key</h2><p className="secret-warning">Copy this key now. It won't be shown again.</p><code className="secret-value">{value.secret}</code><div className="actions"><button className="button" onClick={() => void copy()}>{copied ? "Copied" : "Copy key"}</button><button className="button secondary" onClick={onClose}>Done</button></div></section></div>;
}
