import { useEffect, useState } from "react";
import { api } from "../api";
import { Badge, EmptyState, PageHeader } from "../components";
import { display, explainError, formatCost, formatDuration, formatTokens, protocolLabel, requestStatus } from "../format";
import { useI18n } from "../i18n";
import type { RequestListItem, RequestRecord } from "../types";

export function RequestsPage({ setNotice, setError }: { setNotice: (value: string) => void; setError: (value: string) => void }) {
  const { t, formatDate, locale } = useI18n();
  const [items, setItems] = useState<RequestListItem[]>([]);
  const [total, setTotal] = useState(0);
  const [filters, setFilters] = useState({ model: "", provider: "", status: "", protocol: "" });
  const [selected, setSelected] = useState<RequestRecord | null>(null);
  const [loading, setLoading] = useState(false);
  const load = async () => { try { setLoading(true); const result = await api.requests({ ...filters, limit: 100 }); setItems(result.items); setTotal(result.total); } catch (err) { setError((err as Error).message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [filters.model, filters.provider, filters.status, filters.protocol]);
  useEffect(() => {
    const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load(); }, 3000);
    return () => window.clearInterval(timer);
  }, [filters.model, filters.provider, filters.status, filters.protocol]);
  const clear = async () => { if (!window.confirm(t("requests.confirmClear"))) return; try { await api.clearRequests(); setItems([]); setTotal(0); setSelected(null); setNotice(t("requests.cleared")); } catch (err) { setError((err as Error).message); } };
  const open = (id: string) => void api.request(id).then(setSelected).catch((err: Error) => setError(err.message));
  return <section className="page"><PageHeader eyebrow={t("requests.eyebrow")} title={t("requests.title")} description={t("requests.description")} actions={<><button className="button secondary" onClick={() => void load()} disabled={loading}>{loading ? t("requests.refreshing") : t("common.refresh")}</button><button className="button danger" onClick={() => void clear()}>{t("requests.clearHistory")}</button></>} />
    <div className="request-filters"><input aria-label={t("requests.searchModel")} placeholder={t("requests.searchModel")} value={filters.model} onChange={(event) => setFilters({ ...filters, model: event.target.value })} /><input aria-label={t("requests.filterProvider")} placeholder={t("requests.provider")} value={filters.provider} onChange={(event) => setFilters({ ...filters, provider: event.target.value })} /><select aria-label={t("requests.filterStatus")} value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">{t("requests.allStatuses")}</option><option value="200">200 Success</option><option value="400">400 Error</option><option value="429">429 Error</option><option value="500">500 Error</option></select><select aria-label={t("requests.filterProtocol")} value={filters.protocol} onChange={(event) => setFilters({ ...filters, protocol: event.target.value })}><option value="">{t("requests.allProtocols")}</option><option value="anthropic_messages">Anthropic Messages</option><option value="chat_completions">Chat Completions</option><option value="responses">Responses</option></select></div>
    {items.length === 0 ? <EmptyState title={t("requests.noRequests")} description={t("requests.noRequestsDescription")} /> : <div className="panel table-wrap"><table className="request-table"><thead><tr><th>{t("requests.time")}</th><th>{t("requests.apiKey")}</th><th>{t("requests.model")}</th><th>{t("requests.provider")}</th><th>{t("requests.status")}</th><th className="num">{t("model.latency")}</th><th className="num">{t("requests.cost")}</th><th className="num">{t("requests.tokens")}</th><th>{t("requests.protocol")}</th></tr></thead><tbody>{items.map((item) => { const status = requestStatus(item.status, false, locale); return <tr key={item.id} className="clickable-row" tabIndex={0} onClick={() => open(item.id)} onKeyDown={(event) => { if (event.key === "Enter") open(item.id); }}><td>{formatDate(item.startedAt)}</td><td>{item.accessKeyName ?? "—"}</td><td><strong>{item.model ?? t("common.unknown")}</strong></td><td>{item.enrichmentStatus === "pending" ? <span className="resolving">{t("requests.resolving")}</span> : item.provider ?? t("common.unknown")}</td><td><span className={`request-status ${status.className}`}>{status.label}</span></td><td className="num">{formatDuration(item.durationMs)}</td><td className="num">{formatCost(item.costUsd)}</td><td className="num">{formatTokens(item.promptTokens, item.completionTokens)}</td><td>{protocolLabel(item.protocol, locale)}</td></tr>; })}</tbody></table><small className="request-count">{t("requests.showing", { shown: items.length, total })}</small></div>}
    {selected && <RequestDetail record={selected} onClose={() => setSelected(null)} />}
  </section>;
}

function RoutingStep({ label, providers, isFinal }: { label: string; providers: string[] | null; isFinal?: boolean }) {
  const { t } = useI18n();
  if (!providers || providers.length === 0) return null;
  return <li className={isFinal ? "trace-final" : ""}><span className="trace-label">{label}</span><span className="trace-value">{providers.length === 1 ? providers[0] : t("requests.providersCount", { count: providers.length })}{providers.length > 1 && <small className="mono"> · {providers.join(", ")}</small>}</span></li>;
}

function RequestDetail({ record, onClose }: { record: RequestRecord; onClose: () => void }) {
  const { t, formatDate, locale } = useI18n();
  const policy = record.effectiveProviderPolicy;
  const filterSnapshot = record.providerFilterSnapshot;
  const trace = record.managedRoutingTrace;
  const explanation = explainError(record.error?.code ?? null, locale);
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" role="dialog" aria-label={t("requests.details")} onClick={(event) => event.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">{t("requests.request")}</p><h2><code className="mono">{record.id}</code></h2></div><button className="text-button" onClick={onClose}>{t("common.close")}</button></div>
    <section className="detail-section first"><h3>{t("model.overview")}</h3><dl className="detail-grid"><dt>{t("requests.time")}</dt><dd>{formatDate(record.startedAt)}</dd><dt>{t("requests.apiKey")}</dt><dd>{record.accessKeyName ?? "—"}</dd><dt>{t("requests.protocol")}</dt><dd>{protocolLabel(record.protocol, locale)}</dd><dt>{t("requests.requestedModel")}</dt><dd>{record.requestedModel ?? record.model}</dd><dt>{t("requests.forwardedModel")}</dt><dd>{record.forwardedModel ?? "—"}</dd><dt>{t("requests.actualProvider")}</dt><dd>{record.enrichmentStatus === "pending" ? t("requests.resolving") : record.actualProviderName ?? t("common.unknown")}</dd><dt>{t("requests.status")}</dt><dd>{requestStatus(record.status, record.clientCancelled, locale).label}</dd><dt>{t("requests.streaming")}</dt><dd>{record.streamed === null ? "—" : record.streamed ? t("common.yes") : t("common.no")}</dd><dt>{t("requests.clientCancelled")}</dt><dd>{record.clientCancelled === null ? "—" : record.clientCancelled ? t("common.yes") : t("common.no")}</dd></dl></section>
    <section className="detail-section routing-decision"><h3>{t("requests.routingDecision")}</h3>{trace && <ol className="routing-trace"><RoutingStep label={t("requests.desiredModel")} providers={trace.hardFilter} /><RoutingStep label={t("requests.apiKey")} providers={trace.accessKeyOverride} /><RoutingStep label={t("requests.modelPolicy")} providers={trace.modelPolicy} /><RoutingStep label={t("requests.client")} providers={trace.incoming} /><RoutingStep label={t("requests.final")} providers={trace.final} isFinal /></ol>}{policy ? <><h4>{t("requests.providerPolicyUsed")}</h4><pre>{JSON.stringify(policy, null, 2)}</pre></> : !trace ? <p className="muted">{t("requests.noTrace")}</p> : null}</section>
    <section className="detail-section"><h3>{t("requests.usage")}</h3><dl className="detail-grid"><dt>Prompt tokens</dt><dd>{display(record.promptTokens)}</dd><dt>Completion tokens</dt><dd>{display(record.completionTokens)}</dd><dt>Total tokens</dt><dd>{display(record.totalTokens)}</dd><dt>{t("requests.cost")}</dt><dd>{formatCost(record.costUsd)}</dd><dt>Proxy duration</dt><dd>{formatDuration(record.proxyDurationMs)}</dd><dt>OpenRouter latency</dt><dd>{formatDuration(record.openRouterLatencyMs)}</dd><dt>Generation time</dt><dd>{formatDuration(record.generationTimeMs)}</dd><dt>Finish reason</dt><dd>{display(record.finishReason)}</dd><dt>Generation ID</dt><dd><code className="mono">{display(record.generationId)}</code></dd></dl></section>
    {filterSnapshot && <section className="detail-section"><h3>{t("requests.providerFiltersUsed")}</h3><dl className="detail-grid"><dt>{t("requests.filterStatus")}</dt><dd><Badge variant={record.providerFilterStatus === "fresh" ? "success" : record.providerFilterStatus === "unavailable" ? "danger" : "warning"}>{record.providerFilterStatus ?? t("common.unknown")}</Badge></dd><dt>{t("requests.telemetryAge")}</dt><dd>{record.providerFilterMetadataAgeMs == null ? "—" : formatDuration(record.providerFilterMetadataAgeMs)}</dd><dt>{t("requests.metadataFetched")}</dt><dd>{record.providerFilterMetadataFetchedAt ? formatDate(record.providerFilterMetadataFetchedAt) : "—"}</dd><dt>{t("requests.eligibleEndpoints")}</dt><dd>{record.eligibleProviderRoutingIds?.join(", ") || "—"}</dd></dl></section>}
    {record.error && <section className="detail-section error-copy"><h3>{t("requests.error")}</h3>{record.error.code && <p><Badge variant="danger"><code className="mono">{record.error.code}</code></Badge></p>}{explanation && <p className="error-explanation">{explanation}</p>}{record.error.message && <p>{record.error.message}</p>}</section>}
    <p className="privacy-inline">{t("requests.privacy")}</p></aside></div>;
}
