import { useEffect, useState } from "react";
import { api } from "../api";
import { Badge, EmptyState, PageHeader } from "../components";
import { display, explainError, formatCost, formatDuration, formatTokens, protocolLabel, requestStatus } from "../format";
import type { RequestListItem, RequestRecord } from "../types";

export function RequestsPage({ setNotice, setError }: { setNotice: (value: string) => void; setError: (value: string) => void }) {
  const [items, setItems] = useState<RequestListItem[]>([]);
  const [total, setTotal] = useState(0);
  const [filters, setFilters] = useState({ model: "", provider: "", status: "", protocol: "" });
  const [selected, setSelected] = useState<RequestRecord | null>(null);
  const [loading, setLoading] = useState(false);
  const load = async () => { try { setLoading(true); const result = await api.requests({ ...filters, limit: 100 }); setItems(result.items); setTotal(result.total); } catch (err) { setError((err as Error).message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [filters.model, filters.provider, filters.status, filters.protocol]);
  useEffect(() => {
    const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load(); }, 3000);
    return () => window.clearInterval(timer);
  }, [filters.model, filters.provider, filters.status, filters.protocol]);
  const clear = async () => { if (!window.confirm("Clear all local request metadata? Prompts and responses are never stored.")) return; try { await api.clearRequests(); setItems([]); setTotal(0); setSelected(null); setNotice("Request history cleared."); } catch (err) { setError((err as Error).message); } };
  const open = (id: string) => void api.request(id).then(setSelected).catch((err: Error) => setError(err.message));
  return <section className="page"><PageHeader eyebrow="Activity" title="Requests" description="See exactly what happened to each proxied request. Metadata only — prompts and responses are never stored." actions={<><button className="button secondary" onClick={() => void load()} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</button><button className="button danger" onClick={() => void clear()}>Clear history</button></>} />
    <div className="request-filters"><input aria-label="Search model" placeholder="Search model" value={filters.model} onChange={(event) => setFilters({ ...filters, model: event.target.value })} /><input aria-label="Filter provider" placeholder="Provider" value={filters.provider} onChange={(event) => setFilters({ ...filters, provider: event.target.value })} /><select aria-label="Filter status" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">All statuses</option><option value="200">200 Success</option><option value="400">400 Error</option><option value="429">429 Error</option><option value="500">500 Error</option></select><select aria-label="Filter protocol" value={filters.protocol} onChange={(event) => setFilters({ ...filters, protocol: event.target.value })}><option value="">All protocols</option><option value="anthropic_messages">Anthropic Messages</option><option value="chat_completions">Chat Completions</option><option value="responses">Responses</option></select></div>
    {items.length === 0 ? <EmptyState title="No requests yet" description="Requests made with managed API keys will appear here." /> : <div className="panel table-wrap"><table className="request-table"><thead><tr><th>Time</th><th>API Key</th><th>Model</th><th>Provider</th><th>Status</th><th className="num">Latency</th><th className="num">Cost</th><th className="num">Tokens</th><th>Protocol</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="clickable-row" tabIndex={0} onClick={() => open(item.id)} onKeyDown={(event) => { if (event.key === "Enter") open(item.id); }}><td>{new Date(item.startedAt).toLocaleTimeString()}</td><td>{item.accessKeyName ?? "—"}</td><td><strong>{item.model ?? "Unknown"}</strong></td><td>{item.enrichmentStatus === "pending" ? <span className="resolving">Resolving…</span> : item.provider ?? "Unknown"}</td><td><span className={`request-status ${requestStatus(item.status).className}`}>{requestStatus(item.status).label}</span></td><td className="num">{formatDuration(item.durationMs)}</td><td className="num">{formatCost(item.costUsd)}</td><td className="num">{formatTokens(item.promptTokens, item.completionTokens)}</td><td>{protocolLabel(item.protocol)}</td></tr>)}</tbody></table><small className="request-count">Showing {items.length} of {total}</small></div>}
    {selected && <RequestDetail record={selected} onClose={() => setSelected(null)} />}
  </section>;
}

function RoutingStep({ label, providers, isFinal }: { label: string; providers: string[] | null; isFinal?: boolean }) {
  if (!providers || providers.length === 0) return null;
  return <li className={isFinal ? "trace-final" : ""}><span className="trace-label">{label}</span><span className="trace-value">{providers.length === 1 ? providers[0] : `${providers.length} providers`}{providers.length > 1 && <small className="mono"> · {providers.join(", ")}</small>}</span></li>;
}

function RequestDetail({ record, onClose }: { record: RequestRecord; onClose: () => void }) {
  const policy = record.effectiveProviderPolicy;
  const filterSnapshot = record.providerFilterSnapshot;
  const trace = record.managedRoutingTrace;
  const explanation = explainError(record.error?.code ?? null);
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" role="dialog" aria-label="Request details" onClick={(event) => event.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">Request</p><h2><code className="mono">{record.id}</code></h2></div><button className="text-button" onClick={onClose}>Close</button></div>
    <section className="detail-section first"><h3>Overview</h3><dl className="detail-grid"><dt>Time</dt><dd>{new Date(record.startedAt).toLocaleString()}</dd><dt>API Key</dt><dd>{record.accessKeyName ?? "—"}</dd><dt>Protocol</dt><dd>{protocolLabel(record.protocol)}</dd><dt>Requested model</dt><dd>{record.requestedModel ?? record.model}</dd><dt>Forwarded model</dt><dd>{record.forwardedModel ?? "—"}</dd><dt>Actual provider</dt><dd>{record.enrichmentStatus === "pending" ? "Resolving…" : record.actualProviderName ?? "Unknown"}</dd><dt>Status</dt><dd>{requestStatus(record.status, record.clientCancelled).label}</dd><dt>Streaming</dt><dd>{record.streamed === null ? "—" : record.streamed ? "Yes" : "No"}</dd><dt>Client cancelled</dt><dd>{record.clientCancelled === null ? "—" : record.clientCancelled ? "Yes" : "No"}</dd></dl></section>
    <section className="detail-section routing-decision"><h3>Routing Decision</h3>{trace && <ol className="routing-trace"><RoutingStep label="Desired Model" providers={trace.hardFilter} /><RoutingStep label="API Key" providers={trace.accessKeyOverride} /><RoutingStep label="Model Policy" providers={trace.modelPolicy} /><RoutingStep label="Client" providers={trace.incoming} /><RoutingStep label="Final" providers={trace.final} isFinal /></ol>}{policy ? <><h4>Provider policy used</h4><pre>{JSON.stringify(policy, null, 2)}</pre></> : !trace ? <p className="muted">No routing trace was recorded for this request.</p> : null}</section>
    <section className="detail-section"><h3>Usage</h3><dl className="detail-grid"><dt>Prompt tokens</dt><dd>{display(record.promptTokens)}</dd><dt>Completion tokens</dt><dd>{display(record.completionTokens)}</dd><dt>Total tokens</dt><dd>{display(record.totalTokens)}</dd><dt>Cost</dt><dd>{formatCost(record.costUsd)}</dd><dt>Proxy duration</dt><dd>{formatDuration(record.proxyDurationMs)}</dd><dt>OpenRouter latency</dt><dd>{formatDuration(record.openRouterLatencyMs)}</dd><dt>Generation time</dt><dd>{formatDuration(record.generationTimeMs)}</dd><dt>Finish reason</dt><dd>{display(record.finishReason)}</dd><dt>Generation ID</dt><dd><code className="mono">{display(record.generationId)}</code></dd></dl></section>
    {filterSnapshot && <section className="detail-section"><h3>Provider Filters used</h3><dl className="detail-grid"><dt>Filter status</dt><dd><Badge variant={record.providerFilterStatus === "fresh" ? "success" : record.providerFilterStatus === "unavailable" ? "danger" : "warning"}>{record.providerFilterStatus ?? "Unknown"}</Badge></dd><dt>Telemetry age</dt><dd>{record.providerFilterMetadataAgeMs == null ? "—" : formatDuration(record.providerFilterMetadataAgeMs)}</dd><dt>Metadata fetched</dt><dd>{record.providerFilterMetadataFetchedAt ? new Date(record.providerFilterMetadataFetchedAt).toLocaleString() : "—"}</dd><dt>Eligible endpoints</dt><dd>{record.eligibleProviderRoutingIds?.join(", ") || "—"}</dd></dl></section>}
    {record.error && <section className="detail-section error-copy"><h3>Error</h3>{record.error.code && <p><Badge variant="danger"><code className="mono">{record.error.code}</code></Badge></p>}{explanation && <p className="error-explanation">{explanation}</p>}{record.error.message && <p>{record.error.message}</p>}</section>}
    <p className="privacy-inline">Request metadata only. Prompt and response content are never shown or stored.</p></aside></div>;
}
